# Generated by Django 3.2.12 on 2022-04-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='schema_name',
            field=models.CharField(default='default_schema', max_length=80),
        ),
        migrations.AlterField(
            model_name='schema',
            name='foreign_table',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
