# Generated by Django 3.2.12 on 2022-04-11 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0002_auto_20220410_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='schema',
            name='is_foreign',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='schema',
            name='is_primary',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='schema',
            name='foreign_table',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='rest_api_app.table'),
        ),
    ]
