# Generated by Django 3.2.12 on 2022-04-11 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0003_auto_20220411_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='foreign_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api_app.table'),
        ),
    ]
