# Generated by Django 3.2.13 on 2022-04-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0004_alter_schema_foreign_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='column',
            field=models.CharField(max_length=80),
        ),
    ]
