# Generated by Django 3.2.13 on 2022-04-17 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0005_alter_data_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='column',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='data',
            name='table_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='data',
            name='value',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='schema',
            name='column',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='schema',
            name='foreign_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api_app.table'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='table_name',
            field=models.CharField(max_length=200),
        ),
    ]
